---
- name: import mongodb-org key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D68FA50FEA312927
  tags: install

- name: import mongodb-org repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
    filename: mongodb-org-3.2
  tags: install

- name: install mongodb-org
  package:
    name: "mongodb-org"
    state: present
  tags: install

- name: enable service mongod and ensure it is not masked
  systemd:
    name: mongod
    enabled: yes
    masked: no
  tags: install
